jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Add PII-Data to PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}/PII-Data" >> $GITHUB_ENV
    - name: Run tests
      run: python -m unittest discover -s dags/test -p '*_test.py'




# name: Python Tests
 
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
 
# jobs:
#   build:
 
#     runs-on: ubuntu-latest
 
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python 3.8
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.9
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#     - name: Run unittests
#       run: python -m unittest discover -s dags/test -p '*_test.py'
#     - name: Run pytests
#       run: pytest dags/test
